# Site settings
title: Biased
email: kinger.siddharth@gmail.com
description: The purpose of this blog is to dispel systematic biases about the science of studying biases and ofcourse machine learing"
baseurl: "/Blog"
url: "http://siddharth-kinger.in"
twitter_username: SidKinger
github_username:  kingersid

# Build settings
markdown: kramdown
